name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]  

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [py310]
    steps:
      - name: Fix .gitconfig if it is a directory
        run: |
          if [ -d "$HOME/.gitconfig" ]; then
            rm -rf "$HOME/.gitconfig"
            touch "$HOME/.gitconfig"
          fi
      - name: Configure git
        run: |
          git config --global user.name "CI Runner"
          git config --global user.email "ci@example.com"
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup SSH Agent
        run: |
          # Start SSH agent and set up SSH_AUTH_SOCK
          eval "$(ssh-agent -s)"
          echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV
          echo "SSH agent started with SSH_AUTH_SOCK=$SSH_AUTH_SOCK"
      - uses: prefix-dev/setup-pixi@v0.9.0
        with:
          cache: true
          frozen: true
          environments: ${{ matrix.environment }}
      - name: CI
        run: |
          pixi run -e ${{ matrix.environment }} ci 
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
